//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twainsoft.KeyCatcher.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twainsoft.KeyCatcher.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Key Strokes: --.
        /// </summary>
        internal static string Main_LabelKeyStrokeCount_Current_Key_Strokes {
            get {
                return ResourceManager.GetString("Main_LabelKeyStrokeCount_Current_Key_Strokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Active Since: --.
        /// </summary>
        internal static string Main_LabelStartDate_Session_Active_Since {
            get {
                return ResourceManager.GetString("Main_LabelStartDate_Session_Active_Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s currently an active session. Would you like to close the application and end the session?.
        /// </summary>
        internal static string Main_Main_FormClosing_Active_Session_Message {
            get {
                return ResourceManager.GetString("Main_Main_FormClosing_Active_Session_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Active.
        /// </summary>
        internal static string Main_Main_FormClosing_Session_Active_Title {
            get {
                return ResourceManager.GetString("Main_Main_FormClosing_Session_Active_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Key Strokes: {0}.
        /// </summary>
        internal static string MainForm_CurrentKeyStrokes {
            get {
                return ResourceManager.GetString("MainForm_CurrentKeyStrokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s currently an active session. Would you like to stop it and start a new one?.
        /// </summary>
        internal static string MainForm_KeyboardCatcherOnSessionStarting_Active_Session_Message {
            get {
                return ResourceManager.GetString("MainForm_KeyboardCatcherOnSessionStarting_Active_Session_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Session.
        /// </summary>
        internal static string MainForm_KeyboardCatcherOnSessionStarting_Active_Session_Title {
            get {
                return ResourceManager.GetString("MainForm_KeyboardCatcherOnSessionStarting_Active_Session_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Active Since: {0}.
        /// </summary>
        internal static string MainForm_SessionActiveSince {
            get {
                return ResourceManager.GetString("MainForm_SessionActiveSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon tray {
            get {
                object obj = ResourceManager.GetObject("tray", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
