//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twainsoft.KeyCatcher.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twainsoft.KeyCatcher.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Key Strokes: -- ähnelt.
        /// </summary>
        internal static string Main_LabelKeyStrokeCount_Current_Key_Strokes {
            get {
                return ResourceManager.GetString("Main_LabelKeyStrokeCount_Current_Key_Strokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Session Active Since: -- ähnelt.
        /// </summary>
        internal static string Main_LabelStartDate_Session_Active_Since {
            get {
                return ResourceManager.GetString("Main_LabelStartDate_Session_Active_Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There&apos;s currently an active session. Would you like to close the application and end the session? ähnelt.
        /// </summary>
        internal static string Main_Main_FormClosing_Active_Session_Message {
            get {
                return ResourceManager.GetString("Main_Main_FormClosing_Active_Session_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Session Active ähnelt.
        /// </summary>
        internal static string Main_Main_FormClosing_Session_Active_Title {
            get {
                return ResourceManager.GetString("Main_Main_FormClosing_Session_Active_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Key Strokes: {0} ähnelt.
        /// </summary>
        internal static string MainForm_CurrentKeyStrokes {
            get {
                return ResourceManager.GetString("MainForm_CurrentKeyStrokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There&apos;s currently an active session. Would you like to stop it and start a new one? ähnelt.
        /// </summary>
        internal static string MainForm_KeyboardCatcherOnSessionStarting_Active_Session_Message {
            get {
                return ResourceManager.GetString("MainForm_KeyboardCatcherOnSessionStarting_Active_Session_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active Session ähnelt.
        /// </summary>
        internal static string MainForm_KeyboardCatcherOnSessionStarting_Active_Session_Title {
            get {
                return ResourceManager.GetString("MainForm_KeyboardCatcherOnSessionStarting_Active_Session_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Session Active Since: {0} ähnelt.
        /// </summary>
        internal static string MainForm_SessionActiveSince {
            get {
                return ResourceManager.GetString("MainForm_SessionActiveSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon tray {
            get {
                object obj = ResourceManager.GetObject("tray", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
